spring:
  application:
    name: Kaml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/yadroDB
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: yadro
    create-schemas: true
    default-schema: yadro
server:
  port: 8089